apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: compliance-sentinel-data
  namespace: compliance-sentinel
  labels:
    app: compliance-sentinel
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: compliance-sentinel-logs
  namespace: compliance-sentinel
  labels:
    app: compliance-sentinel
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard