apiVersion: v1
kind: ServiceAccount
metadata:
  name: compliance-sentinel
  namespace: compliance-sentinel
  labels:
    app: compliance-sentinel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: compliance-sentinel
  name: compliance-sentinel-role
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: compliance-sentinel-rolebinding
  namespace: compliance-sentinel
subjects:
  - kind: ServiceAccount
    name: compliance-sentinel
    namespace: compliance-sentinel
roleRef:
  kind: Role
  name: compliance-sentinel-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compliance-sentinel-cluster-role
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/metrics"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: compliance-sentinel-cluster-rolebinding
subjects:
  - kind: ServiceAccount
    name: compliance-sentinel
    namespace: compliance-sentinel
roleRef:
  kind: ClusterRole
  name: compliance-sentinel-cluster-role
  apiGroup: rbac.authorization.k8s.io