apiVersion: v1
kind: Secret
metadata:
  name: compliance-sentinel-secrets
  namespace: compliance-sentinel
type: Opaque
data:
  # Base64 encoded secrets (replace with actual values)
  database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAcG9zdGdyZXM6NTQzMi9jb21wbGlhbmNlX3NlbnRpbmVs
  redis-url: cmVkaXM6Ly9yZWRpczozNjM3OS8w
  secret-key: eW91ci1zZWNyZXQta2V5LWhlcmU=
  jwt-secret: eW91ci1qd3Qtc2VjcmV0LWhlcmU=
---
apiVersion: v1
kind: Secret
metadata:
  name: compliance-sentinel-tls
  namespace: compliance-sentinel
type: kubernetes.io/tls
data:
  # Replace with actual TLS certificate and key
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t...
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: compliance-sentinel
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6InVzZXIiLCJwYXNzd29yZCI6InBhc3MiLCJhdXRoIjoiZFhObGNqcHdZWE56In19fQ==