apiVersion: v1
kind: Service
metadata:
  name: compliance-sentinel-service
  namespace: compliance-sentinel
  labels:
    app: compliance-sentinel
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: compliance-sentinel
---
apiVersion: v1
kind: Service
metadata:
  name: compliance-sentinel-headless
  namespace: compliance-sentinel
  labels:
    app: compliance-sentinel
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: compliance-sentinel
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: compliance-sentinel-ingress
  namespace: compliance-sentinel
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - compliance-sentinel.example.com
      secretName: compliance-sentinel-tls
  rules:
    - host: compliance-sentinel.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: compliance-sentinel-service
                port:
                  number: 8000