# ConfigMap for Compliance Sentinel Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: compliance-sentinel-config
  namespace: compliance-sentinel
  labels:
    app.kubernetes.io/name: compliance-sentinel
    app.kubernetes.io/component: config
data:
  # Core system configuration
  COMPLIANCE_SENTINEL_ENVIRONMENT: "production"
  COMPLIANCE_SENTINEL_DEBUG_ENABLED: "false"
  COMPLIANCE_SENTINEL_LOG_LEVEL: "INFO"
  COMPLIANCE_SENTINEL_LOG_FORMAT: "json"
  COMPLIANCE_SENTINEL_LOG_DESTINATION: "stdout"
  
  # Performance settings
  COMPLIANCE_SENTINEL_MAX_CONCURRENT_ANALYSES: "3"
  COMPLIANCE_SENTINEL_MAX_FILE_SIZE_MB: "10"
  COMPLIANCE_SENTINEL_REQUEST_TIMEOUT_SECONDS: "30.0"
  COMPLIANCE_SENTINEL_WORKER_THREADS: "4"
  
  # Cache configuration
  COMPLIANCE_SENTINEL_CACHE_ENABLED: "true"
  COMPLIANCE_SENTINEL_CACHE_TTL: "3600"
  COMPLIANCE_SENTINEL_CACHE_MAX_SIZE: "1000"
  COMPLIANCE_SENTINEL_CACHE_CLEANUP_INTERVAL: "300"
  COMPLIANCE_SENTINEL_CACHE_BACKEND: "redis"
  COMPLIANCE_SENTINEL_REDIS_HOST: "redis-service"
  COMPLIANCE_SENTINEL_REDIS_PORT: "6379"
  COMPLIANCE_SENTINEL_REDIS_DB: "0"
  COMPLIANCE_SENTINEL_REDIS_SSL: "false"
  
  # Circuit breaker settings
  COMPLIANCE_SENTINEL_CIRCUIT_BREAKER_ENABLED: "true"
  COMPLIANCE_SENTINEL_CIRCUIT_BREAKER_FAILURE_THRESHOLD: "5"
  COMPLIANCE_SENTINEL_CIRCUIT_BREAKER_RECOVERY_TIMEOUT: "60"
  COMPLIANCE_SENTINEL_CIRCUIT_BREAKER_SUCCESS_THRESHOLD: "3"
  
  # External API endpoints
  COMPLIANCE_SENTINEL_NVD_BASE_URL: "https://services.nvd.nist.gov/rest/json"
  COMPLIANCE_SENTINEL_CVE_BASE_URL: "https://cve.circl.lu/api"
  COMPLIANCE_SENTINEL_OSV_BASE_URL: "https://api.osv.dev"
  COMPLIANCE_SENTINEL_GITHUB_ADVISORY_URL: "https://api.github.com/advisories"
  
  # API rate limiting
  COMPLIANCE_SENTINEL_NVD_RATE_LIMIT: "50"
  COMPLIANCE_SENTINEL_CVE_RATE_LIMIT: "100"
  COMPLIANCE_SENTINEL_OSV_RATE_LIMIT: "200"
  COMPLIANCE_SENTINEL_GITHUB_RATE_LIMIT: "5000"
  
  # MCP Server configuration
  MCP_HOST: "0.0.0.0"
  MCP_PORT: "8000"
  MCP_WORKERS: "4"
  MCP_API_KEY_REQUIRED: "true"
  MCP_CORS_ENABLED: "false"
  MCP_RATE_LIMIT_REQUESTS: "100"
  MCP_RATE_LIMIT_WINDOW: "60"
  MCP_RATE_LIMIT_BURST: "20"
  MCP_REQUEST_TIMEOUT_SECONDS: "30.0"
  MCP_MAX_REQUEST_SIZE_MB: "10"
  MCP_DEFAULT_SEARCH_LIMIT: "50"
  MCP_MAX_SEARCH_LIMIT: "100"
  MCP_CACHE_TTL_SECONDS: "1800"
  MCP_CACHE_MAX_ENTRIES: "10000"
  
  # JWT configuration
  COMPLIANCE_SENTINEL_AUTH_JWT_ALGORITHM: "HS256"
  COMPLIANCE_SENTINEL_AUTH_JWT_EXPIRY_HOURS: "24"
  COMPLIANCE_SENTINEL_AUTH_JWT_ISSUER: "compliance-sentinel-k8s"
  
  # API key configuration
  COMPLIANCE_SENTINEL_AUTH_API_KEY_LENGTH: "64"
  COMPLIANCE_SENTINEL_AUTH_API_KEY_PREFIX: "cs_k8s_"
  COMPLIANCE_SENTINEL_AUTH_API_KEY_EXPIRY_DAYS: "90"
  
  # Password policy
  COMPLIANCE_SENTINEL_AUTH_MIN_PASSWORD_LENGTH: "12"
  COMPLIANCE_SENTINEL_AUTH_REQUIRE_SPECIAL_CHARS: "true"
  COMPLIANCE_SENTINEL_AUTH_REQUIRE_NUMBERS: "true"
  COMPLIANCE_SENTINEL_AUTH_REQUIRE_UPPERCASE: "true"
  
  # Session management
  COMPLIANCE_SENTINEL_AUTH_SESSION_TIMEOUT_MINUTES: "60"
  COMPLIANCE_SENTINEL_AUTH_MAX_FAILED_ATTEMPTS: "3"
  COMPLIANCE_SENTINEL_AUTH_LOCKOUT_DURATION_MINUTES: "30"
  
  # Secret management (using Kubernetes secrets)
  COMPLIANCE_SENTINEL_SECRET_MANAGER_TYPE: "kubernetes"
  COMPLIANCE_SENTINEL_SECRET_ROTATION_ENABLED: "true"
  COMPLIANCE_SENTINEL_SECRET_ROTATION_INTERVAL_DAYS: "30"
  COMPLIANCE_SENTINEL_SECRET_CACHE_TTL: "300"
  
  # File monitoring
  COMPLIANCE_SENTINEL_FILE_WATCHER_ENABLED: "true"
  COMPLIANCE_SENTINEL_FILE_WATCHER_DEBOUNCE_MS: "1000"
  COMPLIANCE_SENTINEL_FILE_WATCHER_MAX_FILES: "1000"
  COMPLIANCE_SENTINEL_FILE_WATCHER_PATTERNS: "*.py,*.js,*.ts,*.java,*.go,*.rb,*.php"
  COMPLIANCE_SENTINEL_FILE_MAX_SIZE_MB: "10"
  COMPLIANCE_SENTINEL_FILE_EXCLUDE_PATTERNS: "node_modules/**,*.min.js,*.map,__pycache__/**"
  
  # Monitoring and metrics
  COMPLIANCE_SENTINEL_METRICS_ENABLED: "true"
  COMPLIANCE_SENTINEL_METRICS_PORT: "9090"
  COMPLIANCE_SENTINEL_METRICS_PATH: "/metrics"
  COMPLIANCE_SENTINEL_METRICS_COLLECTION_INTERVAL: "30"
  
  # Health check
  COMPLIANCE_SENTINEL_HEALTH_CHECK_ENABLED: "true"
  COMPLIANCE_SENTINEL_HEALTH_CHECK_PORT: "8080"
  COMPLIANCE_SENTINEL_HEALTH_CHECK_PATH: "/health"
  
  # Alerting thresholds
  COMPLIANCE_SENTINEL_ALERT_ERROR_RATE_THRESHOLD: "0.05"
  COMPLIANCE_SENTINEL_ALERT_RESPONSE_TIME_THRESHOLD: "5000"
  COMPLIANCE_SENTINEL_ALERT_MEMORY_USAGE_THRESHOLD: "0.85"
  COMPLIANCE_SENTINEL_ALERT_CPU_USAGE_THRESHOLD: "0.80"
  
  # CLI configuration
  COMPLIANCE_SENTINEL_CLI_VERBOSE: "false"
  COMPLIANCE_SENTINEL_CLI_COLORS: "false"
  COMPLIANCE_SENTINEL_CLI_PROGRESS: "false"
  COMPLIANCE_SENTINEL_CLI_OUTPUT_FORMAT: "json"
  COMPLIANCE_SENTINEL_CLI_DEFAULT_PATTERN: "**/*.{py,js,ts,java,go,rb,php}"
  COMPLIANCE_SENTINEL_CLI_MAX_FILES: "10000"
  COMPLIANCE_SENTINEL_CLI_SEVERITY_THRESHOLD: "medium"
  
  # Audit logging
  COMPLIANCE_SENTINEL_AUDIT_ENABLED: "true"
  COMPLIANCE_SENTINEL_AUDIT_LOG_FORMAT: "json"
  COMPLIANCE_SENTINEL_AUDIT_RETENTION_DAYS: "365"
  
  # Compliance frameworks
  COMPLIANCE_SENTINEL_COMPLIANCE_FRAMEWORKS: "SOC2,PCI-DSS,GDPR,HIPAA"
  COMPLIANCE_SENTINEL_COMPLIANCE_REPORTING_ENABLED: "true"
  COMPLIANCE_SENTINEL_COMPLIANCE_REPORT_INTERVAL_HOURS: "24"