# Kubernetes Secrets for Compliance Sentinel
# Note: In production, use external secret management systems like:
# - AWS Secrets Manager with External Secrets Operator
# - HashiCorp Vault with Vault Secrets Operator
# - Azure Key Vault with Secret Store CSI Driver

apiVersion: v1
kind: Secret
metadata:
  name: compliance-sentinel-secrets
  namespace: compliance-sentinel
  labels:
    app.kubernetes.io/name: compliance-sentinel
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # JWT Secret (base64 encoded)
  # Generate with: openssl rand -base64 64 | tr -d '\n' | base64 -w 0
  COMPLIANCE_SENTINEL_AUTH_JWT_SECRET: <BASE64_ENCODED_JWT_SECRET>
  
  # Redis Password (base64 encoded)
  COMPLIANCE_SENTINEL_REDIS_PASSWORD: <BASE64_ENCODED_REDIS_PASSWORD>
  
  # Database credentials (if using database)
  COMPLIANCE_SENTINEL_DB_USER: <BASE64_ENCODED_DB_USER>
  COMPLIANCE_SENTINEL_DB_PASSWORD: <BASE64_ENCODED_DB_PASSWORD>
  
  # External API keys (base64 encoded)
  COMPLIANCE_SENTINEL_NVD_API_KEY: <BASE64_ENCODED_NVD_API_KEY>
  COMPLIANCE_SENTINEL_GITHUB_TOKEN: <BASE64_ENCODED_GITHUB_TOKEN>

---
# TLS Secret for HTTPS
apiVersion: v1
kind: Secret
metadata:
  name: compliance-sentinel-tls
  namespace: compliance-sentinel
  labels:
    app.kubernetes.io/name: compliance-sentinel
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  # TLS certificate and key (base64 encoded)
  tls.crt: <BASE64_ENCODED_TLS_CERTIFICATE>
  tls.key: <BASE64_ENCODED_TLS_PRIVATE_KEY>

---
# Example using External Secrets Operator with AWS Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: compliance-sentinel
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: compliance-sentinel-sa

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: compliance-sentinel-external-secrets
  namespace: compliance-sentinel
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: compliance-sentinel-secrets
    creationPolicy: Owner
  data:
  - secretKey: COMPLIANCE_SENTINEL_AUTH_JWT_SECRET
    remoteRef:
      key: compliance-sentinel/prod/jwt-secret
      property: secret
  - secretKey: COMPLIANCE_SENTINEL_REDIS_PASSWORD
    remoteRef:
      key: compliance-sentinel/prod/redis-password
      property: password
  - secretKey: COMPLIANCE_SENTINEL_DB_PASSWORD
    remoteRef:
      key: compliance-sentinel/prod/database
      property: password
  - secretKey: COMPLIANCE_SENTINEL_NVD_API_KEY
    remoteRef:
      key: compliance-sentinel/prod/nvd-api-key
      property: key
  - secretKey: COMPLIANCE_SENTINEL_GITHUB_TOKEN
    remoteRef:
      key: compliance-sentinel/prod/github-token
      property: token